[package]
name = "compress_office"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.14"
zip = "2.1"
image = { version = "0.25", features = ["jpeg", "png"] }
anyhow = "1.0"
native-dialog = "0.7"

[build-dependencies]
slint-build = "1.14"
